# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-05 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAccountManagement',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100, null=True)),
                ('account_number', models.CharField(max_length=100, null=True)),
                ('account_email', models.CharField(max_length=100, null=True)),
                ('account_url', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarkdownArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_time_c', models.DateField(auto_now_add=True, null=True)),
                ('article_time_u', models.DateField(auto_now=True, null=True)),
                ('article_classification', models.CharField(max_length=50, null=True)),
                ('article_title', models.CharField(max_length=50, null=True)),
                ('article_img', models.CharField(max_length=50, null=True)),
                ('article_content', mdeditor.fields.MDTextField(null=True)),
            ],
        ),
    ]
