# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-14 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAccountManagement',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100, null=True)),
                ('account_number', models.CharField(max_length=100, null=True)),
                ('account_email', models.CharField(max_length=100, null=True)),
                ('account_url', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('content', mdeditor.fields.MDTextField()),
                ('content_test', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MarkdownArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', markdownx.models.MarkdownxField()),
                ('article_time_c', models.DateField(auto_now_add=True, null=True)),
                ('article_time_u', models.DateField(auto_now=True, null=True)),
                ('article_label', models.CharField(max_length=50, null=True)),
                ('article_title', models.CharField(max_length=50, null=True)),
                ('article_img', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
