# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_time_c', models.DateField(auto_now_add=True)),
                ('article_time_u', models.DateField(auto_now=True)),
                ('article_label', models.CharField(max_length=50)),
                ('article_title', models.CharField(max_length=50)),
                ('article_img', models.CharField(max_length=50)),
                ('article_content', models.TextField(null=True)),
            ],
        ),
    ]
