# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAccountManagement',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100, null=True)),
                ('account_number', models.CharField(max_length=100, null=True)),
                ('account_email', models.CharField(max_length=100, null=True)),
                ('account_url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
